-- FlightDesk (CS425) relational schema
-- Designed to mirror the TypeScript domain types in `lib/models/types.ts`

BEGIN;

-- Drop in dependency order for easy rebuilds during demos.
DROP TABLE IF EXISTS api_rate_limit CASCADE;
DROP TABLE IF EXISTS booking_flight CASCADE;
DROP TABLE IF EXISTS booking CASCADE;
DROP TABLE IF EXISTS flight_cabin_inventory CASCADE;
DROP TABLE IF EXISTS flight_price CASCADE;
DROP TABLE IF EXISTS flight CASCADE;
DROP TABLE IF EXISTS credit_card CASCADE;
DROP TABLE IF EXISTS address CASCADE;
DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS airline CASCADE;
DROP TABLE IF EXISTS airport CASCADE;

-- airport (IATA code as PK)
CREATE TABLE airport (
  airport_code TEXT PRIMARY KEY,
  airport_name TEXT NOT NULL,
  city TEXT NOT NULL,
  region TEXT NOT NULL,
  country TEXT NOT NULL,
  timezone TEXT NOT NULL
);

-- airline
CREATE TABLE airline (
  airline_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  iata_code TEXT NOT NULL UNIQUE,
  airline_name TEXT NOT NULL
);

-- customer (identified by email; optional password_hash for session login)
CREATE TABLE customer (
  customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  phone TEXT NULL,
  password_hash TEXT NULL
);

-- address (belongs to customer)
CREATE TABLE address (
  address_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES customer(customer_id) ON DELETE CASCADE,
  line1 TEXT NOT NULL,
  line2 TEXT NULL,
  city TEXT NOT NULL,
  region TEXT NOT NULL,
  postal_code TEXT NOT NULL,
  country TEXT NOT NULL,
  is_primary BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX address_customer_id_idx ON address(customer_id);

-- Ensure at most one primary address per customer
CREATE UNIQUE INDEX address_one_primary_per_customer_idx
  ON address(customer_id)
  WHERE is_primary;

-- credit_card (belongs to customer; billing address must belong to same customer)
CREATE TABLE credit_card (
  credit_card_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES customer(customer_id) ON DELETE CASCADE,
  billing_address_id INTEGER NOT NULL REFERENCES address(address_id) ON DELETE RESTRICT,
  card_brand TEXT NOT NULL,
  last_four TEXT NOT NULL CHECK (char_length(last_four) = 4),
  exp_month INTEGER NOT NULL CHECK (exp_month >= 1 AND exp_month <= 12),
  exp_year INTEGER NOT NULL CHECK (exp_year >= 2000)
);

CREATE INDEX credit_card_customer_id_idx ON credit_card(customer_id);

-- flight (scheduled segment)
CREATE TABLE flight (
  flight_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  airline_id INTEGER NOT NULL REFERENCES airline(airline_id) ON DELETE RESTRICT,
  flight_number TEXT NOT NULL,
  origin_airport_code TEXT NOT NULL REFERENCES airport(airport_code) ON DELETE RESTRICT,
  destination_airport_code TEXT NOT NULL REFERENCES airport(airport_code) ON DELETE RESTRICT,
  scheduled_departure TIMESTAMPTZ NOT NULL,
  scheduled_arrival TIMESTAMPTZ NOT NULL,
  duration_minutes INTEGER NOT NULL CHECK (duration_minutes > 0),
  CONSTRAINT flight_od_not_same CHECK (origin_airport_code <> destination_airport_code)
);

CREATE INDEX flight_od_departure_idx
  ON flight(origin_airport_code, destination_airport_code, scheduled_departure);

-- cabin inventory (enforced on booking / released on cancel)
CREATE TABLE flight_cabin_inventory (
  flight_id INTEGER NOT NULL REFERENCES flight(flight_id) ON DELETE CASCADE,
  cabin_class TEXT NOT NULL CHECK (cabin_class IN ('economy', 'first')),
  seats_total INTEGER NOT NULL CHECK (seats_total >= 0),
  seats_booked INTEGER NOT NULL DEFAULT 0 CHECK (seats_booked >= 0 AND seats_booked <= seats_total),
  PRIMARY KEY (flight_id, cabin_class)
);

CREATE INDEX flight_cabin_inventory_flight_id_idx ON flight_cabin_inventory(flight_id);

-- flight_price (1 row per cabin class)
CREATE TABLE flight_price (
  flight_price_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  flight_id INTEGER NOT NULL REFERENCES flight(flight_id) ON DELETE CASCADE,
  cabin_class TEXT NOT NULL CHECK (cabin_class IN ('economy', 'first')),
  currency_code TEXT NOT NULL DEFAULT 'USD' CHECK (char_length(currency_code) = 3),
  amount NUMERIC(10,2) NOT NULL CHECK (amount >= 0),
  CONSTRAINT flight_price_unique_cabin UNIQUE (flight_id, cabin_class)
);

CREATE INDEX flight_price_flight_id_idx ON flight_price(flight_id);

-- Enforce: first-class price must be greater than economy price for the same flight.
-- (Done via trigger so we can compare across rows.)
CREATE OR REPLACE FUNCTION enforce_first_class_pricing()
RETURNS TRIGGER AS $$
DECLARE
  econ NUMERIC(10,2);
  first NUMERIC(10,2);
BEGIN
  SELECT amount INTO econ
  FROM flight_price
  WHERE flight_id = NEW.flight_id AND cabin_class = 'economy';

  SELECT amount INTO first
  FROM flight_price
  WHERE flight_id = NEW.flight_id AND cabin_class = 'first';

  -- If either cabin is missing, allow insert/update; the constraint will be checked
  -- once both rows exist.
  IF econ IS NULL OR first IS NULL THEN
    RETURN NEW;
  END IF;

  IF first <= econ THEN
    RAISE EXCEPTION 'Invalid pricing for flight_id %: first (%.2f) must be > economy (%.2f)',
      NEW.flight_id, first, econ;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS flight_price_enforce_first_gt_econ ON flight_price;
CREATE TRIGGER flight_price_enforce_first_gt_econ
  AFTER INSERT OR UPDATE OF amount ON flight_price
  FOR EACH ROW
  EXECUTE FUNCTION enforce_first_class_pricing();

-- booking (header)
CREATE TABLE booking (
  booking_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES customer(customer_id) ON DELETE RESTRICT,
  credit_card_id INTEGER NOT NULL REFERENCES credit_card(credit_card_id) ON DELETE RESTRICT,
  booked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  booking_status TEXT NOT NULL CHECK (booking_status IN ('confirmed', 'cancelled', 'pending')),
  currency_code TEXT NOT NULL DEFAULT 'USD' CHECK (char_length(currency_code) = 3),
  total_amount NUMERIC(10,2) NOT NULL CHECK (total_amount >= 0)
);

CREATE INDEX booking_customer_id_idx ON booking(customer_id);
CREATE INDEX booking_booked_at_idx ON booking(booked_at DESC);

-- booking_flight (segments)
CREATE TABLE booking_flight (
  booking_flight_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id INTEGER NOT NULL REFERENCES booking(booking_id) ON DELETE CASCADE,
  flight_id INTEGER NOT NULL REFERENCES flight(flight_id) ON DELETE RESTRICT,
  segment_number INTEGER NOT NULL CHECK (segment_number >= 1),
  cabin_class TEXT NOT NULL CHECK (cabin_class IN ('economy', 'first')),
  fare_amount NUMERIC(10,2) NOT NULL CHECK (fare_amount >= 0),
  CONSTRAINT booking_flight_unique_segment UNIQUE (booking_id, segment_number)
);

CREATE INDEX booking_flight_booking_id_idx ON booking_flight(booking_id);

-- Simple DB-backed rate limiting (per-route keys; truncate to UTC minute buckets)
CREATE TABLE api_rate_limit (
  rate_key TEXT NOT NULL,
  window_start TIMESTAMPTZ NOT NULL,
  hit_count INTEGER NOT NULL DEFAULT 0 CHECK (hit_count >= 0),
  PRIMARY KEY (rate_key, window_start)
);

CREATE INDEX api_rate_limit_window_cleanup_idx ON api_rate_limit (window_start);

-- Cross-table consistency: credit_card.billing_address_id must belong to same customer.
CREATE OR REPLACE FUNCTION enforce_credit_card_billing_address_customer()
RETURNS TRIGGER AS $$
DECLARE
  addr_customer_id INTEGER;
BEGIN
  SELECT customer_id INTO addr_customer_id
  FROM address
  WHERE address_id = NEW.billing_address_id;

  IF addr_customer_id IS NULL THEN
    RAISE EXCEPTION 'billing_address_id % does not exist', NEW.billing_address_id;
  END IF;

  IF addr_customer_id <> NEW.customer_id THEN
    RAISE EXCEPTION 'billing_address_id % belongs to customer %, not customer %',
      NEW.billing_address_id, addr_customer_id, NEW.customer_id;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS credit_card_billing_address_customer ON credit_card;
CREATE TRIGGER credit_card_billing_address_customer
  BEFORE INSERT OR UPDATE OF billing_address_id, customer_id ON credit_card
  FOR EACH ROW
  EXECUTE FUNCTION enforce_credit_card_billing_address_customer();

COMMIT;

